[env:teensy41-performance]
platform = teensy
board = teensy41
framework = arduino
lib_deps =
    ssilverman/QNEthernet
upload_protocol = teensy-cli
monitor_speed = 115200
extra_scripts = pre:scripts/find_teensy.py

[env:teensy41]
extends = env:teensy41-performance
build_flags = -DDEBUG_SERIAL
